### ISSUE TITLE
Show server donation target for specified period in time

### ISSUE THREAD

**Issue by FlorianSW** [FlorianSW/server-donation-tool#18]
> Something that would be a cool optional feature would be a visible donation goal that shows how much has been donated towards the goal.

Such a feature requires to hold some meta information of donations for a specific period of time (at least the donation date as well as the amount of the donation).

The configuration could look like:
- Set a target amount of donations
- Specify a timeframe in days?
- Specify the start date of a month?

**Comment by TWModern** [comment]
Would be a great addition!

**Comment by FlorianSW** [comment]
@TWModern How would you like to configure the donation target, though? :/ Having it manually each time (like setting the "end date" and the target amount?). Or a recurring target (like every month or so)?

**Comment by lewk-io** [comment]
@FlorianSW I imagine something like x money by y day of the month.

So if a user wanted to raise $300 by the 1st

**Comment by FlorianSW** [comment]
@lewk-io would that be a one-time target only? Or a recurring one? So, 300$ until the 1st of the month, each month?

**Comment by lewk-io** [comment]
@FlorianSW recurring monthly i believe.

I think the use case Modern has is when a community may want to drive donations to cover that months costs, as most subscriptions are monthly (server hosting, discord bots etc)

**Comment by FlorianSW** [comment]
@lewk-io @TWModern sorry to ping you both :) Is that in the right direction of what you expected?
![image](https://user-images.githubusercontent.com/4892966/128065085-711ad54b-e5b9-498c-8478-100766e34088.png)

Any feedback/suggestions so far? :)

**Comment by FlorianSW** [comment]
There were no changes to the way the donation target is made public on the website.

However, to make the connection between the community and the donation website clearer, I've added an additional, optional feature:
![image](https://user-images.githubusercontent.com/4892966/128604368-a45e7069-267b-4c7c-8217-3543db0df4c5.png)

The donation target can be mirrored to a discord channel of your choice (as long as the bot has write access to it, ofc :P). I'll add some remaining documentation. Also: If there are any more information needed in this discord message, just give me a comment here :)

**Comment by lewk-io** [comment]
Great idea mate. Looks really good!

**Comment by TWModern** [comment]
Agreed! Looks great!

**Comment by FlorianSW** [comment]
Awesome, thanks for the feedback :) I released the recent changes in a new version:
https://github.com/FlorianSW/server-donation-tool/releases/tag/v1.1.0

I'll close this issue for now. Please, if you have further suggestions on how to improve this or other features of the tool, feel free to open a new issue :)
