### ISSUE TITLE
Support Google Analytics

### ISSUE THREAD

**Issue by lewk-io** [FlorianSW/server-donation-tool#22]
Either somewhere to dump their html tags or just their GA ID would be great

**Comment by FlorianSW** [comment]
Hmm, collecting this data in GA would require some kind of privacy policy as well :/ At least a link would be required for that as well.

**Comment by lewk-io** [comment]
Does Google provide a generic one?

**Comment by FlorianSW** [comment]
I think they provide some general information on a page to link to. I think the best would be to have a generic Privacy policy within the tool (also explaining what data the tool is processing itself) and adding a GA section, if it is configured, automatically. In that way, server hosters could also change the wording if needed.
