### ISSUE TITLE
Add whitelisting as a perk

### ISSUE THREAD

**Issue by lewk-io** [FlorianSW/server-donation-tool#29]
It'd be good if it could be "for x number of days" and/or "until x date"

**Comment by FlorianSW** [comment]
What would that perk be for then? I mean, do you have a bit more context? Like, would it be a donation perk which grants access to a private server or such?

**Comment by lewk-io** [comment]
So I've been thinking of running a couple of custom events to raise money for charity. So the intention would be that people donate to get access to the event and then the proceeds go to charity

**Comment by FlorianSW** [comment]
Fixed by https://github.com/FlorianSW/server-donation-tool/commit/16ec1e363290ca2ea269b0ce8ffb883cfffd7be0 (mentioned the wrong issue in the commit message 🙈).
