### ISSUE TITLE
Feature request: add price to discord notifitcation when amount type is "VARIABLE"

### ISSUE THREAD

**Issue by mr190e** [FlorianSW/server-donation-tool#60]
Right now when people donate using a variable input the amount of money is not being showed in the discord notification. Therefore its impossible to determine how much money was sent. On our server we use the variable input to collect money for custom skins and other custom ingame gear. Our GFX artists should be able to check wether someone paid the correct amount of money using the variable price package :)

**Comment by FlorianSW** [comment]
Hi 👋 
This will be included in the next release (it's already in the main branch).
